#!/usr/bin/env python3
"""Render a vault's wikilink graph as a themeable inline SVG for the landing page.

The docs/ landing page shows the shape of a real vault. A screenshot of Obsidian's
graph view would work, but it bakes in one theme, ships a raster asset, and puts
private page titles on a public site. This draws the same graph from the same data
and emits SVG instead: node labels are never rendered, colours come from the page's
CSS custom properties, and the result costs no extra network request.

Layout is seeded, so re-running against an unchanged vault reproduces the same
picture byte for byte. Pass --seed to try a different arrangement if the default
one packs badly.

    python scripts/graph-svg.py ~/Documents/my-wiki
    python scripts/graph-svg.py ~/Documents/my-wiki --svg-only /tmp/graph.svg
"""

import argparse
import math
import random
import re
import sys
from pathlib import Path

# Mirrors llm_wiki.lint so the graph counts the same pages the linter does, plus
# _inbox (immutable sources, not wiki pages) and _meta (templates and dashboards).
SKIP_DIRS = frozenset(
    "_raw _archived _staging _archives _inbox _meta .obsidian .git".split()
)
# Bookkeeping pages link to nearly everything. Drawing them collapses the graph
# into one hub and hides how the knowledge itself connects.
SKIP_STEMS = frozenset({"index", "log", "hot", "_insights", "readme"})

WIKILINK_RE = re.compile(r"\[\[([^\]|#]+?)(?:[|#][^\]]*?)?\]\]")

START = "<!-- graph:start (generated by scripts/graph-svg.py) -->"
END = "<!-- graph:end -->"


def collect_pages(vault):
    """Map lowercased page stem to path, skipping system folders and bookkeeping."""
    pages = {}
    for path in vault.rglob("*.md"):
        parts = path.relative_to(vault).parts
        if any(part in SKIP_DIRS for part in parts):
            continue
        if path.stem.lower() in SKIP_STEMS:
            continue
        pages[path.stem.lower()] = path
    return pages


def collect_edges(pages):
    """Return sorted unique undirected edges between pages that both exist."""
    edges = set()
    for stem, path in pages.items():
        try:
            text = path.read_text(encoding="utf-8", errors="replace")
        except OSError as exc:
            print(f"warning: cannot read {path}: {exc}", file=sys.stderr)
            continue
        for raw in WIKILINK_RE.findall(text):
            target = raw.strip().split("/")[-1].lower()
            # Links to pages that do not exist are lint's problem, not the graph's.
            if target in pages and target != stem:
                edges.add(tuple(sorted((stem, target))))
    return sorted(edges)


def layout(nodes, edges, seed, iterations=420, canvas=600.0):
    """Fruchterman-Reingold on a square canvas, with gravity to keep it framed."""
    rng = random.Random(seed)
    pos = {n: [rng.uniform(0.15, 0.85) * canvas, rng.uniform(0.15, 0.85) * canvas]
           for n in nodes}
    k = math.sqrt(canvas * canvas / max(len(nodes), 1)) * 0.62
    temp = canvas / 6.0
    centre = canvas / 2

    for _ in range(iterations):
        disp = {n: [0.0, 0.0] for n in nodes}

        for i, u in enumerate(nodes):
            for v in nodes[i + 1:]:
                dx, dy = pos[u][0] - pos[v][0], pos[u][1] - pos[v][1]
                dist2 = dx * dx + dy * dy
                if dist2 < 1e-6:
                    dx, dy, dist2 = rng.uniform(-1, 1), rng.uniform(-1, 1), 1.0
                dist = math.sqrt(dist2)
                push = (k * k) / dist
                ux, uy = dx / dist * push, dy / dist * push
                disp[u][0] += ux; disp[u][1] += uy
                disp[v][0] -= ux; disp[v][1] -= uy

        for a, b in edges:
            dx, dy = pos[a][0] - pos[b][0], pos[a][1] - pos[b][1]
            dist = math.hypot(dx, dy) or 0.01
            pull = (dist * dist) / k
            ux, uy = dx / dist * pull, dy / dist * pull
            disp[a][0] -= ux; disp[a][1] -= uy
            disp[b][0] += ux; disp[b][1] += uy

        for n in nodes:
            disp[n][0] += (centre - pos[n][0]) * 0.012
            disp[n][1] += (centre - pos[n][1]) * 0.012
            travel = math.hypot(*disp[n]) or 0.01
            step = min(travel, temp)
            pos[n][0] += disp[n][0] / travel * step
            pos[n][1] += disp[n][1] / travel * step

        temp *= 0.972
    return pos


def fit(pos, nodes, pad=14.0, span=600.0):
    """Scale uniformly into a tight bounding box; returns positions plus viewBox size."""
    xs = [pos[n][0] for n in nodes]
    ys = [pos[n][1] for n in nodes]
    minx, maxx, miny, maxy = min(xs), max(xs), min(ys), max(ys)
    scale = span / max(maxx - minx, maxy - miny, 1e-6)
    placed = {n: ((pos[n][0] - minx) * scale + pad, (pos[n][1] - miny) * scale + pad)
              for n in nodes}
    width = (maxx - minx) * scale + 2 * pad
    height = (maxy - miny) * scale + 2 * pad
    return placed, width, height


def render_svg(nodes, edges, pos, degree, width, height):
    """Emit the SVG. No <text> is produced: page titles must never reach the page."""
    peak = max(degree.values())
    lines = [
        f'<svg class="graph-svg" viewBox="0 0 {width:.0f} {height:.0f}" role="img"',
        f'     aria-label="Link graph of a working vault: {len(nodes)} pages joined by'
        f' {len(edges)} links." xmlns="http://www.w3.org/2000/svg">',
        '  <g class="graph-edges">',
    ]
    for a, b in edges:
        x1, y1 = pos[a]
        x2, y2 = pos[b]
        lines.append(f'    <line x1="{x1:.1f}" y1="{y1:.1f}" x2="{x2:.1f}" y2="{y2:.1f}"/>')
    lines.append("  </g>")
    lines.append('  <g class="graph-nodes">')
    for node in nodes:
        x, y = pos[node]
        radius = 2.6 + 5.4 * (degree[node] / peak) ** 0.65
        lines.append(f'    <circle cx="{x:.1f}" cy="{y:.1f}" r="{radius:.1f}"/>')
    lines.append("  </g>")
    lines.append("</svg>")
    return "\n".join(lines)


def splice(page, block):
    """Replace the marked region of the HTML page, keeping the markers in place."""
    html = page.read_text(encoding="utf-8")
    start, end = html.find(START), html.find(END)
    if start == -1 or end == -1:
        raise SystemExit(
            f"error: {page} is missing the {START!r} / {END!r} markers.\n"
            "       Add them inside <figure class=\"graph\"> and re-run."
        )
    if end < start:
        raise SystemExit(f"error: {page} has the graph markers in reverse order.")
    updated = html[:start + len(START)] + "\n" + block + "\n      " + html[end:]
    page.write_text(updated, encoding="utf-8")


def main():
    parser = argparse.ArgumentParser(
        description="Render a vault's wikilink graph into the landing page as inline SVG."
    )
    parser.add_argument("vault", type=Path, help="path to the Obsidian vault")
    parser.add_argument(
        "--out", type=Path,
        default=Path(__file__).resolve().parent.parent / "docs" / "index.html",
        help="HTML page to splice into (default: docs/index.html)",
    )
    parser.add_argument("--svg-only", type=Path, metavar="PATH",
                        help="write a standalone .svg here instead of touching the page")
    parser.add_argument("--seed", type=int, default=7, help="layout seed (default: 7)")
    args = parser.parse_args()

    vault = args.vault.expanduser()
    if not vault.is_dir():
        raise SystemExit(f"error: vault not found: {vault}")

    pages = collect_pages(vault)
    if not pages:
        raise SystemExit(f"error: no wiki pages found under {vault}")

    edges = collect_edges(pages)
    if not edges:
        raise SystemExit(
            f"error: {len(pages)} pages found but no wikilinks between them. "
            "Nothing to draw."
        )

    nodes = sorted({n for edge in edges for n in edge})
    degree = dict.fromkeys(nodes, 0)
    for a, b in edges:
        degree[a] += 1
        degree[b] += 1

    pos, width, height = fit(layout(nodes, edges, args.seed), nodes)
    svg = render_svg(nodes, edges, pos, degree, width, height)

    print(f"pages scanned : {len(pages)}")
    print(f"nodes drawn   : {len(nodes)} ({len(pages) - len(nodes)} unlinked, omitted)")
    print(f"edges drawn   : {len(edges)}")
    print(f"viewBox       : {width:.0f} x {height:.0f}")

    if args.svg_only:
        args.svg_only.write_text(svg, encoding="utf-8")
        print(f"\nwrote {args.svg_only}")
        return 0

    # The caption states counts, so it is generated too. Editing it by hand would
    # let the numbers drift away from the graph beside them.
    block = (
        f'      <div class="graph-body">{svg}</div>\n'
        f"      <figcaption>\n"
        f"        {len(nodes)} pages and the {len(edges)} links between them, drawn from"
        f" a real vault.\n"
        f"        Every edge was written by an agent and is readable as plain markdown.\n"
        f"      </figcaption>"
    )
    splice(args.out, block)
    print(f"\nupdated {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
